on:
  release:
    types: [published]

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: delete test and docs dir
      run: rm -rf test docs COPYING
    - name: Upload asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .
        asset_name: asset-name.zip
        asset_content_type: application/zip


